[project]
name = "installector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litellm==1.60.5",
    "prompt-toolkit>=3.0.50",
    "pygments>=2.19.1",
    "rich>=13.9.4",
]
